"""followers

Revision ID: 6697b91a4126
Revises: 0931fbdb317e
Create Date: 2023-07-30 12:15:37.441587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6697b91a4126'
down_revision = '0931fbdb317e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
