"""add age

Revision ID: 71af0857cbc7
Revises: feafd18ba839
Create Date: 2023-07-18 09:24:50.841062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71af0857cbc7'
down_revision = 'feafd18ba839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###
